Collapse MLP layers in configuration files
MLH-Fellowship/vissl pull request #9
Opened 2021-02-24 03:20 UTC by akainth015

Resolves #5

2021-02-27 18:57 UTC, prigoyal requested changes
thank you for the PR @akainth015 and @grace-omotoso .  :) 

There is an issue with the current changes in `mlp.py`. As we discussed in the task https://github.com/MLH-Fellowship/vissl/issues/5, we have to add the check `if i == (len(dims) - 2): break` mandatory. If we don't add the check, then we introduce some unintended layers ReLU in the model. My suggestion is to follow something along the lines of what's proposed in the #5 .

Concretely, follow the 3 steps next:
1. Make changes to the `mlp.py` following the screenshot 
<img width="612" alt="Screen Shot 2021-02-27 at 1 53 46 PM" src="https://user-images.githubusercontent.com/13488275/109397182-7f262080-7903-11eb-8602-5f0bd6cff951.png">

2. Make changes to the files in this folder https://github.com/facebookresearch/vissl/tree/master/configs/config/pretrain/pirl/models following the screenshot
<img width="838" alt="Screen Shot 2021-02-27 at 1 54 52 PM" src="https://user-images.githubusercontent.com/13488275/109397200-96fda480-7903-11eb-8017-ffe81958fc9b.png">

3. Make changes to the files in folder https://github.com/facebookresearch/vissl/tree/master/configs/config/pretrain/jigsaw following the screenshot 
<img width="797" alt="Screen Shot 2021-02-27 at 1 54 26 PM" src="https://user-images.githubusercontent.com/13488275/109397212-a8df4780-7903-11eb-9f71-72ccd9177a3e.png">

2021-02-27 18:57 UTC, prigoyal commented on tests/test_tasks.py
> +from .utils import UNIT_TEST_CONFIGS, SSLHydraConfig
just curious, what's the motivation for this change?

2021-02-27 21:36 UTC, akainth015 commented
Okay, I have made the changes. you asked for. To be frank though, I am still a bit confused by what result this is expected to produce. The current code, given the following MLP param:
```
[3,4,5,6] Use BN, Use ReLU = False, Skip Last BN ReLU
```
seems as if it would generate the following network
```
Linear(3, 4) -> BN -> Linear (3, 5) -> BN -> Linear(3, 6)
```
because `last_dim` is never updated since ReLU is False.

My understanding is that it should generate the following, hence the reasoning behind my code changes.
```
Linear(3, 3) -> BN -> Linear (3 , 4) -> BN -> Linear(4,5)
```

2021-03-01 13:10 UTC, prigoyal commented
> Okay, I have made the changes. you asked for. To be frank though, I am still a bit confused by what result this is expected to produce. The current code, given the following MLP param:
> 
> ```
> [3,4,5,6] Use BN, Use ReLU = False, Skip Last BN ReLU
> ```
> 
> seems as if it would generate the following network
> 
> ```
> Linear(3, 4) -> BN -> Linear (3, 5) -> BN -> Linear(3, 6)
> ```
> 
> because `last_dim` is never updated since ReLU is False.
> 
> My understanding is that it should generate the following, hence the reasoning behind my code changes.
> 
> ```
> Linear(3, 3) -> BN -> Linear (3 , 4) -> BN -> Linear(4,5)
> ```

excellent catch @akainth015 :) We should move the `last_dim = dim` update from line73 our of the `if` conditional and always update the `last_dim`. That should fix. For the example above,

`[3,4,5,6] Use BN=true, Use ReLU = False, Skip Last BN ReLU` -> should give us 

```
Linear(3, 4) -> BN -> Linear (4, 5) -> BN -> Linear(5, 6)
```

2021-03-01 13:12 UTC, prigoyal commented
looks great overall. just one last update remaining to `last_dim = dim` moving out of `if` conditional and all good to go otherwise :)

2021-03-02 11:45 UTC, prigoyal approved these changes
looks AMAZING!!! thank you @grace-omotoso and @akainth015 :) you guys rock!!

2021-03-02 11:46 UTC, merged